/**
 * Seeded, synthetic stadium graph and a match-day crowd dataset.
 *
 * The challenge provides no live venue APIs, so the app ships with a realistic
 * seeded bowl (gates, a two-level concourse, step-free and stepped transitions,
 * seating, facilities, and exits) plus a kickoff-rush crowd feed. Operators can
 * replace the crowd feed at runtime by uploading their own CSV/JSON. All data
 * here is validated by `parseGraph` before use, so it can never desync from the
 * schema the engine expects.
 */

import type { StadiumGraphData } from './types';

/** Minute-of-day markers for the seeded crowd feed (09:00 / 10:00 / 11:00). */
export const SEED_TIMES = { early: 540, kickoff: 600, late: 660 } as const;

/** Default origin/destination used to showcase a crowd-avoiding detour. */
export const DEMO_ROUTE = {
  originId: 'gate-n',
  destinationId: 'seat-acc-a',
  minuteOfDay: SEED_TIMES.kickoff,
} as const;

export const DEFAULT_STADIUM: StadiumGraphData = {
  nodes: [
    { id: 'gate-n', label: 'North Gate', kind: 'gate', x: 50, y: 8 },
    { id: 'gate-e', label: 'East Gate', kind: 'gate', x: 92, y: 50 },
    { id: 'gate-s', label: 'South Gate', kind: 'gate', x: 50, y: 92 },
    { id: 'gate-w', label: 'West Gate', kind: 'gate', x: 8, y: 50 },
    { id: 'lc-n', label: 'North Concourse', kind: 'concourse', x: 50, y: 22 },
    { id: 'lc-ne', label: 'North-East Concourse', kind: 'concourse', x: 70, y: 30 },
    { id: 'lc-e', label: 'East Concourse', kind: 'concourse', x: 78, y: 50 },
    { id: 'lc-se', label: 'South-East Concourse', kind: 'concourse', x: 70, y: 70 },
    { id: 'lc-s', label: 'South Concourse', kind: 'concourse', x: 50, y: 78 },
    { id: 'lc-sw', label: 'South-West Concourse', kind: 'concourse', x: 30, y: 70 },
    { id: 'lc-w', label: 'West Concourse', kind: 'concourse', x: 22, y: 50 },
    { id: 'lc-nw', label: 'North-West Concourse', kind: 'concourse', x: 30, y: 30 },
    { id: 'uc-n', label: 'Upper North', kind: 'concourse', x: 50, y: 36 },
    { id: 'uc-e', label: 'Upper East', kind: 'concourse', x: 64, y: 50 },
    { id: 'uc-s', label: 'Upper South', kind: 'concourse', x: 50, y: 64 },
    { id: 'uc-w', label: 'Upper West', kind: 'concourse', x: 36, y: 50 },
    { id: 'seat-101', label: 'Section 101 (Lower)', kind: 'seat', x: 82, y: 36 },
    { id: 'seat-115', label: 'Section 115 (Lower)', kind: 'seat', x: 26, y: 64 },
    { id: 'seat-201', label: 'Section 201 (Upper)', kind: 'seat', x: 50, y: 46 },
    { id: 'seat-acc-a', label: 'Accessible Platform A', kind: 'seat', x: 86, y: 56 },
    { id: 'fac-restroom', label: 'Accessible Restroom', kind: 'facility', x: 14, y: 58 },
    { id: 'fac-firstaid', label: 'First Aid Point', kind: 'facility', x: 44, y: 88 },
    { id: 'fac-food', label: 'Halal Food Court', kind: 'facility', x: 84, y: 66 },
    { id: 'exit-w', label: 'West Exit', kind: 'exit', x: 2, y: 50 },
    { id: 'exit-s', label: 'South Exit', kind: 'exit', x: 50, y: 98 },
  ],
  edges: [
    {
      from: 'gate-n',
      to: 'lc-n',
      distanceMeters: 28,
      mode: 'level',
      widthMeters: 4,
      bidirectional: true,
    },
    {
      from: 'gate-e',
      to: 'lc-e',
      distanceMeters: 24,
      mode: 'level',
      widthMeters: 4,
      bidirectional: true,
    },
    {
      from: 'gate-s',
      to: 'lc-s',
      distanceMeters: 24,
      mode: 'level',
      widthMeters: 4,
      bidirectional: true,
    },
    {
      from: 'gate-w',
      to: 'lc-w',
      distanceMeters: 24,
      mode: 'level',
      widthMeters: 4,
      bidirectional: true,
    },
    {
      from: 'lc-n',
      to: 'lc-ne',
      distanceMeters: 30,
      mode: 'level',
      widthMeters: 3.2,
      bidirectional: true,
    },
    {
      from: 'lc-ne',
      to: 'lc-e',
      distanceMeters: 28,
      mode: 'level',
      widthMeters: 3.2,
      bidirectional: true,
    },
    {
      from: 'lc-e',
      to: 'lc-se',
      distanceMeters: 28,
      mode: 'level',
      widthMeters: 3.2,
      bidirectional: true,
    },
    {
      from: 'lc-se',
      to: 'lc-s',
      distanceMeters: 30,
      mode: 'level',
      widthMeters: 3.2,
      bidirectional: true,
    },
    {
      from: 'lc-s',
      to: 'lc-sw',
      distanceMeters: 30,
      mode: 'level',
      widthMeters: 3.2,
      bidirectional: true,
    },
    {
      from: 'lc-sw',
      to: 'lc-w',
      distanceMeters: 28,
      mode: 'level',
      widthMeters: 3.2,
      bidirectional: true,
    },
    {
      from: 'lc-w',
      to: 'lc-nw',
      distanceMeters: 28,
      mode: 'level',
      widthMeters: 3.2,
      bidirectional: true,
    },
    {
      from: 'lc-nw',
      to: 'lc-n',
      distanceMeters: 30,
      mode: 'level',
      widthMeters: 3.2,
      bidirectional: true,
    },
    {
      from: 'lc-n',
      to: 'uc-n',
      distanceMeters: 14,
      mode: 'stairs',
      widthMeters: 1.8,
      bidirectional: true,
    },
    {
      from: 'lc-w',
      to: 'uc-w',
      distanceMeters: 16,
      mode: 'elevator',
      widthMeters: 2.2,
      bidirectional: true,
    },
    {
      from: 'lc-s',
      to: 'uc-s',
      distanceMeters: 20,
      mode: 'ramp',
      widthMeters: 2.6,
      bidirectional: true,
    },
    {
      from: 'lc-e',
      to: 'uc-e',
      distanceMeters: 15,
      mode: 'escalator',
      widthMeters: 1.1,
      bidirectional: true,
    },
    {
      from: 'uc-n',
      to: 'uc-e',
      distanceMeters: 26,
      mode: 'level',
      widthMeters: 2.8,
      bidirectional: true,
    },
    {
      from: 'uc-e',
      to: 'uc-s',
      distanceMeters: 26,
      mode: 'level',
      widthMeters: 2.8,
      bidirectional: true,
    },
    {
      from: 'uc-s',
      to: 'uc-w',
      distanceMeters: 26,
      mode: 'level',
      widthMeters: 2.8,
      bidirectional: true,
    },
    {
      from: 'uc-w',
      to: 'uc-n',
      distanceMeters: 26,
      mode: 'level',
      widthMeters: 2.8,
      bidirectional: true,
    },
    {
      from: 'seat-101',
      to: 'lc-ne',
      distanceMeters: 12,
      mode: 'level',
      widthMeters: 2,
      bidirectional: true,
    },
    {
      from: 'seat-115',
      to: 'lc-sw',
      distanceMeters: 12,
      mode: 'level',
      widthMeters: 2,
      bidirectional: true,
    },
    {
      from: 'seat-201',
      to: 'uc-n',
      distanceMeters: 10,
      mode: 'level',
      widthMeters: 2,
      bidirectional: true,
    },
    {
      from: 'seat-acc-a',
      to: 'lc-e',
      distanceMeters: 10,
      mode: 'level',
      widthMeters: 2.6,
      bidirectional: true,
    },
    {
      from: 'fac-restroom',
      to: 'lc-w',
      distanceMeters: 10,
      mode: 'level',
      widthMeters: 1.6,
      bidirectional: true,
    },
    {
      from: 'fac-firstaid',
      to: 'lc-s',
      distanceMeters: 12,
      mode: 'level',
      widthMeters: 1.6,
      bidirectional: true,
    },
    {
      from: 'fac-food',
      to: 'lc-se',
      distanceMeters: 12,
      mode: 'level',
      widthMeters: 1.6,
      bidirectional: true,
    },
    {
      from: 'exit-w',
      to: 'gate-w',
      distanceMeters: 10,
      mode: 'level',
      widthMeters: 4,
      bidirectional: true,
    },
    {
      from: 'exit-s',
      to: 'gate-s',
      distanceMeters: 10,
      mode: 'level',
      widthMeters: 4,
      bidirectional: true,
    },
  ],
};
